// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVcnBRARj8F-Shvmy2Die7j1qC_Wroqto',
    appId: '1:670342594452:web:9b68f86ad9702d632b9981',
    messagingSenderId: '670342594452',
    projectId: 'cultureandartapp',
    authDomain: 'cultureandartapp.firebaseapp.com',
    storageBucket: 'cultureandartapp.appspot.com',
    measurementId: 'G-Y7YVGJ2T6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQbCbV0WXRVmyKDM26WnWGANgkOHRoq4U',
    appId: '1:670342594452:android:ba47fe82481a0bb22b9981',
    messagingSenderId: '670342594452',
    projectId: 'cultureandartapp',
    storageBucket: 'cultureandartapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUPXCOZD3lMu8lIJSgaO471o5eR8dkoUs',
    appId: '1:670342594452:ios:469b3a910c02c7f82b9981',
    messagingSenderId: '670342594452',
    projectId: 'cultureandartapp',
    storageBucket: 'cultureandartapp.appspot.com',
    iosClientId: '670342594452-57r89ik5klu5lojvctp4053vkbbn13uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cultureArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUPXCOZD3lMu8lIJSgaO471o5eR8dkoUs',
    appId: '1:670342594452:ios:469b3a910c02c7f82b9981',
    messagingSenderId: '670342594452',
    projectId: 'cultureandartapp',
    storageBucket: 'cultureandartapp.appspot.com',
    iosClientId: '670342594452-57r89ik5klu5lojvctp4053vkbbn13uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cultureArt',
  );
}
